# Generated by Django 3.1.3 on 2020-12-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
    ]
