# Generated by Django 3.1.3 on 2020-12-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20201229_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
