# Generated by Django 3.1.3 on 2020-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20201230_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
