# Generated by Django 3.1.3 on 2021-01-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20201231_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
    ]
